### PR TITLE
Card UI

### PR DESCRIPTION
**Pull request by Meyanis95**
Dumb card UI for display in PCD wallet

### CODE REVIEW

**Review by vuvoth — COMMENTED** [review]
Could you show a screenshot of the UI card?

**Comment by Meyanis95** [comment]
I still need to finish integrating partially the Identity SDK to the Zupass repo locally to display the card.
So it's a temporary UI for the moment, it is following the `'@pcd/passport-ui'` guidelines.
I'll send you screenshots once the integration is working :) so we can postpone the validation of this PR if you prefer.

**Comment by vuvoth** [comment]
> > Could you show a screenshot of the UI card?
> 
> Screenshot 2023-06-29 at 19 14 15
> 
> Here you will find a screenshot of the rendering. The terms `exp` and `mod` are a bit odd, but we can change them in the future.

It look great! Is it show information about proving action?

**Comment by Meyanis95** [comment]
What do you mean by 'proving action'?
This card show the PCD representing the aadhaar proof.
For the action of proving it's another card and the UI is implemented directly in the Zupass repo.

**Comment by vuvoth** [comment]
> What do you mean by 'proving action'? This card show the PCD representing the aadhaar proof. For the action of proving it's another card and the UI is implemented directly in the Zupass repo.

Thanks! The UI show verify action, right?

**Comment by Meyanis95** [comment]
Not in the PCD card.

**Comment by vuvoth** [comment]
I am confusing, but I will rethink again. BTW I approved this PR. 
Thanks <3

**Comment by vuvoth** [comment]
I am confusing, but I will rethink again. BTW I approved this PR. 
Thanks <3

**Review by vuvoth — APPROVED** [review]

**Pull request merged**
